[workspace]
authors = ["Patrick Sadil <psadil@gmail.com>"]
channels = ["conda-forge"]
name = "synthstrip_app"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mpi4py = "3.1.6.*"
networkx = "<4"
nibabel = "<6"
nilearn = "<0.14"
numpy = "<3"
polars = "<2"
pyarrow = "<24"
pydantic = "<3"
scikit-image = "<0.27"
scikit-learn = "<2"
pytorch = "2.1.2.*"
pillow = "<13"
xxhash = ">=0.8.3,<0.9"
python = "3.10.*"
surfa = ">=0.6.3,<0.7"
typing_extensions = ">=4.15.0,<5"
ucx = "1.17.0.*"
rdma-core = "52.0.*"
impi_rt = "2021.12.*"

[pypi-dependencies]
biomarkers = { git = "https://github.com/a2cps/biomarker-extractor.git", rev = "a55dd5e" }
