[app]
name = logphantom_app
label = logphantom_app
description = log phantom phantom scans
version = 0.1
storage_system = a2cps.storage-frontera-protected
hpc_system = a2cps.hpc-frontera-protected
queue = corralextra
bundle = assets

[docker]
dockerfile = Dockerfile
organization = psadil
repo = phantomdb
tag = 0.1

[env]

[git]
branch = master
; remote = 

[grants]
; read = 
; execute = 
; update = 

[job]
