---
logs:
  level: DEBUG
  token: ~
heudiconv:
  appId: heudiconv
  appVersion: 3.1.3
  name: heudiconv_test
  archive: true
  archiveSystemDir: testing/actor-heudiconv
  archiveSystemId: secure.frontera
  execSystemId: secure.frontera
  maxMinutes: 300
  parameterSet:
    envVariables:
      - key: FILES
        value: /scratch/05369/urrutia/a2cps_test/NS_northshore/dicoms/QC_NS030624QA.zip
      - key: LIST_OF_SUBJECTS
        value: --subjects nsphantom
      - key: SESSION_FOR_LONGITUDINAL
        value: --ses 240306
      - key: DEVICE_SERIAL_NUMBER
        value: 1a
  subscriptions:
    - description: Message on Failure
      enabled: true
      eventCategoryFilter: JOB_ERROR_MESSAGE
      deliveryTargets: 
        - deliveryMethod: WEBHOOK
          deliveryAddress: ~
pipelines:
  fmriprep_alias: fmriprep.prod
  api_server: https://portals-api.tacc.utexas.edu
  mriqc_alias: mriqc.prod
  vbr_actor_alias: vbr-actor.prod
  heudiconv_alias: heudiconv_router.prod
  qsiprep_alias: qsiprep.prod
  cat_alias: cat.prod
  qaphantom_alias: qaphantom.prod
  fslanat_alias: fslanat.prod
