---
logs:
  level: DEBUG
  token: ~
heudiconv:
  appId: urrutia-heudiconv-0.9.0.2
  name: heudiconv_test
  archive: true
  archivePath: testing/actor-heudiconv
  maxRunTime: "11:59:00"
  parameters:
    FILES: norshore/bids/1
    LIST_OF_SUBJECTS: sub-01
    OUTDIR: '.'
    SESSION_FOR_LONGITUDINAL: session1
    BIDS: true
    HEURISTIC: a2cps.py
    LOCATOR: =''
    SITE: ""

  notifications:
    -
      event: FINISHED
      url: a2cps-dirc-notify-ui@a2cps.org
pipelines:
  fmriprep_alias: fmriprep.prod
  api_server: https://portals-api.tacc.utexas.edu
  mriqc_alias: mriqc.prod
  bids_validator_alias: bids-validator.prod
  vbr_actor_alias: vbr-actor.prod
  heudiconv_alias: heudiconv_router.prod
