---
debug: false

logs:
  level: DEBUG
  token: ~

main:
  appId: urrutia-logphantom-0.1
  name: logphantom_job
  archive: false
  archivePath: ''
  maxRunTime: "01:00:00"
  parameters:
    BIDS: "/corral-secure/projects/A2CPS/community/resources/imaging/phantom/bids"
    BIND_DIR: "/corral-secure/projects/A2CPS"
    PRODUCTS: "/corral-secure/projects/A2CPS/products/mris"
    POST: "--post"
    
