import os
import re
import argparse
import requests
from typing import Union, Optional

import pandas as pd
import numpy as np

from atlassian import Confluence

SITE_CODES = {
  "UI": "UI_uic",
  "NS": "NS_northshore",
  "UC": "UC_uchicago",
  "UM": "UM_umichigan",
  "WS": "WS_wayne_state",
  "SH": "SH_spectrum_health"
  }


def _zscore(scores: np.array) -> np.array:
  return (scores - scores.mean()) / scores.std()


def _format_url(url: str, text: str = "link") -> str:
  return f'<a href="{url}">{text}</a>'


def post_notification(notification: str, confluence: Optional[Confluence] = None) -> None:
  if confluence is not None:
    # print(notification)
    confluence.update_page(
      page_id="25755998", 
      title="QC Aggregation", 
      body=notification, 
      parent_id=None, 
      type='page', 
      representation='storage', 
      minor_edit=True)
  else:
    print(notification)
  return 


def build_notification(outliers: pd.DataFrame, notification: list[str]) -> str:
  for site, small in outliers.sort_index().groupby(level=0):
    notification.append(f"<h3>{site}</h3>")
    for idx, row in small.sort_index().iterrows():
      notification.append(f'<p>{idx[-1]}: {row.dropna().to_dict()}</p>')
  #   for sub, d in outliers.groupby(level=-1):
  #     notification.append(f'<p>{d.dropna(axis=1).to_json(orient="index")}</p>')
  # # for idx, row in outliers.sort_index().iterrows():
    

  return '\n'.join(notification)


def get_outliers(
  d: pd.DataFrame, 
  groups: list[str], 
  # url_root: str = "https://prod.a2cps.tacc.utexas.edu/workbench/data/tapis/projects/a2cps.project.PHI-PRODUCTS/mris",
  url_root: str = "https://confluence.a2cps.org/download/attachments/25755998",
  # imaging_log: Union[str, bytes, os.PathLike] = os.path.join('corral-secure', 'projects', 'A2CPS', 'shared', 'urrutia', 'imaging_report', 'imaging_log.csv')
  imaging_log: Union[str, bytes, os.PathLike] = os.path.join('/home', 'psadil', 'Documents', 'git', 'a2cps', 'mri_imaging_pipeline', 'qc_aggregator_app', 'tests', 'imaging_log.csv')
  ) -> pd.DataFrame:
  '''
  get_outliers(fname=pd.read_csv('group_T1w.tsv', delimiter="\t"))
  get_outliers(fname=pd.read_csv('group_T1w.tsv', delimiter="\t"), ['site'])
  '''
  
  sites = (
    pd.read_csv(
      imaging_log,
      usecols=['subject_id', 'site'])
    .rename(columns={'subject_id':'sub'})
    .drop_duplicates())
  dind = d[['bids_name']].copy()
  dind['sub'] = [int(re.findall('sub-(\d+)', x)[0]) for x in dind['bids_name']]
  dind['ses'] = [re.findall('ses-(V\d)', x)[0] for x in dind['bids_name']]

  if 'task' in groups:
    indices = ['site', 'sub', 'task', 'ses', 'bids_name']
    dind['task'] = [re.findall('task-(\w+)_', x)[0] for x in dind['bids_name']]
  else:
    indices = ['site', 'sub', 'ses', 'bids_name']

  dind = dind.merge(sites, on='sub', how='left')

  outliers = (
    d
    .merge(dind, on=['bids_name'])
    .set_index(indices)
    .groupby(groups)
    .transform(lambda x: np.where(np.abs(_zscore(x))>3, x, np.nan))
    .dropna(how="all")
    .round(1)
    )
  outliers['url'] = [f"{url_root}/{bids_name}.html?api=v2" for bids_name in outliers.index.get_level_values('bids_name')]
  # outliers['url'] = [
  #   f"{url_root}/{SITE_CODES[site]}/mriqc/{site}{sub}{ses}" for site,sub,ses in 
  #     zip(outliers.index.get_level_values('site'), outliers.index.get_level_values('sub'), outliers.index.get_level_values('ses'))]
  outliers['url'] = outliers.apply(lambda x: _format_url(x.url), axis=1)
      
  return outliers
  

def main(
  t1w_fname: Union[str, bytes, os.PathLike], 
  bold_fname: Union[str, bytes, os.PathLike],
  dwi_fname: Union[str, bytes, os.PathLike],
  report_html: str = "qc_report.html",
  token: Optional[str] = None, 
  pem: Optional[Union[str, bytes, os.PathLike]] = None) -> None:

  anat_outliers = get_outliers(
    d=pd.read_csv(t1w_fname, delimiter="\t"), 
    groups=['site'])
  func_outliers = get_outliers(
    d=pd.read_csv(bold_fname, delimiter="\t"),
    groups=['site', 'task'])
  dwi_outliers = get_outliers(
    d=pd.read_csv(dwi_fname).rename(columns={"file_name": "bids_name"}).drop(columns=["subject_id", "acq_id", "task_id", "dir_id", "space_id", "rec_id", "session_id", "run_id"]), 
    groups=['site'])

  # func_outliers.to_csv('outliers_bold.csv')
  # anat_outliers.to_csv('outliers_T1w.csv')

  anat_notification = build_notification(anat_outliers, ['<h1>T1w</h1>'])
  func_notification = build_notification(func_outliers, ['<h1>bold</h1>'])
  dwi_notification = build_notification(dwi_outliers, ['<h1>dwi</h1>'])

  header = """
  <h1>Instructions</h1>
  <p>This page is automatically generated. Please do not edit by hand!</p>
  <p>It is generated by the qc_aggregator_app, which is run daily. The app aggregates
  qc metrics from MRIQC and QSIprep and uses these to flag individual scans as outliers.
  Scans are flagged as outliers when any of the calculated metrics deviates substantially
  from the site-wise average. Any scan that has been flagged warrants review 
  (e.g., by looking at the MRIQC, fMRIPrep, or QSIprep html report).
  To record when a scan has been reviewed, see the "QC Log" page.</p>
  <h3>Summary</h3>
  <ul>
    <li> This page is generated automatically and should not be edited by hand. </li>
    <li> Scans are listed here if they are flagged as being an outlier (which doesn't necessarily mean it's a poor scan). </li>
    <li> Unreviewed scans should be reviewed, and the review should be logged in the QC Log (logging to be done manually). </li>
  </ul>
  """

  notification = ''.join([
    header,
    f'<p>{_format_url(f"https://confluence.a2cps.org/download/attachments/25755998/group_T1w.html?api=v2", text="group_T1w.html")}</p>',
    f'<p>{_format_url(f"https://confluence.a2cps.org/download/attachments/25755998/group_bold.html?api=v2", text="group_bold.html")}</p>',
    f'<p>{_format_url(f"https://confluence.a2cps.org/download/attachments/25755998/{report_html}?api=v2", text="qc_report.html")}</p>', 
    anat_notification, 
    func_notification, 
    dwi_notification])
  # notification = ' '.join([anat_notification, t1w_plot])

  if token is not None:
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {token}"})
    s.verify = pem
    post_notification(
      notification, 
      Confluence(
        url='https://confluence.a2cps.org',
        cloud=True,
        session=s))
  else:
    post_notification(notification)

  return


if __name__ == '__main__':

  """
  python check_qc.py MRIQC_A2CPS_group_T1w.tsv MRIQC_A2CPS_group_bold.tsv --token "$(<.token)"
  """

  parser = argparse.ArgumentParser(description='check mriqc-group output for outliers')
  parser.add_argument(
    't1w_fname', 
    default='group_T1w.tsv',
    help="group level tsv for T1w images")
  parser.add_argument(
    'bold_fname', 
    default='group_bold.tsv',
    help="group level tsv for bold images")
  parser.add_argument(
    'dwi_fname', 
    default='group_dwi.csv',
    help="group level csv for dwi images")
  parser.add_argument(
    '--token', 
    type=str)
  parser.add_argument(
    '--pem', 
    type=str)

  args = parser.parse_args()
  main(args.t1w_fname, args.bold_fname, args.dwi_fname, token=args.token, pem=args.pem)
