#!/bin/bash
#SBATCH -J heudiconv-ref
#SBATCH -o heudiconv-ref.out
#SBATCH -e heudiconv-ref.err
#SBATCH -t 6:00:00
#SBATCH -p corralextra
#SBATCH -N 1 -n 1
#SBATCH -A A2CPS

# this is for running the newest heudiconv_app
# with real participants for generating the reference
# bids jsons with phantoms

module load tacc-apptainer
module unload xalt

BIND_DIR=/corral-secure/projects/A2CPS
CONTAINER_IMAGE=psadil/heudiconv_app
# shellcheck disable=SC2089
LOCATOR='--locator="" '
HEURISTIC="--heuristic a2cps.py "
BIDS="--bids "
DELETE_DUPLICATES=1
POST="--no-post "
CHECK_JSONS=1
project=/corral-secure/projects/A2CPS/products/mris
DICOMS=(
    "${project}"/NS_northshore/dicoms/NS10920V1.zip
    "${project}"/NS_northshore/dicoms/QC_NS012324QA.zip
    "${project}"/RU_rush/dicoms/RU10945V1.zip
    "${project}"/RU_rush/dicoms/QC_RU022324QA.zip
    "${project}"/SH_spectrum_health/dicoms/SH25441V1.zip
    "${project}"/SH_spectrum_health/dicoms/QC_SH050224QA.zip
    "${project}"/UC_uchicago/dicoms/UC10885V1.zip
    "${project}"/UC_uchicago/dicoms/QC_UC011024QA.zip
    "${project}"/UI_uic/dicoms/UI10910V1.zip
    "${project}"/UI_uic/dicoms/QC_UI083123QA.zip
    "${project}"/UM_umichigan/dicoms/UM20369V1.zip # UM1
    "${project}"/UM_umichigan/dicoms/UM25245V1.zip  # UM2
    /corral-secure/projects/A2CPS/products/development/mris/UM_umichigan/dicoms/UM02081322QA.zip
    "${project}"/WS_wayne_state/dicoms/WS25225V1.zip
    "${project}"/WS_wayne_state/dicoms/QC_WS010824QA.zip
    "${project}"/UM_umichigan/dicoms/UM20340V3.zip  # scan with variable ShimSetting
    )
SUBJECTS=(            10920 nsphantom 10945  ruphantom 25441 shphantom 10885 ucphantom 10910            uiphantom        20369            25245             umphantom        25225 wsphantom 20340)
SITES=(               NS    NS        RU     RU        SH    SH        UC    UC        UI               UI               UM               UM                UM               WS    WS        UM)
SES=(                 V1    012324    V1     041125    V1    050224    V1    011024    V1               083123           V1               V1                081322           V1    010824    V3)
DEVICE_SERIAL_NUMBER=(70032 70032     166295 166295    66022 66022     71399 71399     000000312996MR3T 000000312996MR3T 000000000UM750MR 0007347633TMRFIX  0007347633TMRFIX 40292 40292     0007347633TMRFIX)

declare -A SITE_LONG=(
    [NS]=NS_northshore
    [RU]=RU_rush
    [SH]=SH_spectrum_health 
    [UC]=UC_uchicago 
    [UI]=UI_uic 
    [UM]=UM_umichigan 
    [WS]=WS_wayne_state
    )

# do this once to cache before parallelism
apptainer run docker://"${CONTAINER_IMAGE}" ls


for i in "${!SUBJECTS[@]}"; do
    if [[ "${SUBJECTS[${i}]}" == *phantom* ]]; then
        sublong="QC_${SITES[${i}]}${SUBJECTS[${i}]}${SES[${i}]}QA"
    else
        sublong="${SITES[${i}]}${SUBJECTS[${i}]}${SES[${i}]}"
    fi
    apptainer run \
        --env ANON_CMD="",BIDS="${BIDS}",CHECK_JSONS="${CHECK_JSONS}",CONVERTED_OUTDIR="",CONVERTER="--converter dcm2niix",DATALAD="",DCMCONFIG="",DELETE_DUPLICATES="${DELETE_DUPLICATES}",DICOM_DIR_TEMPLATE="",FILES="${DICOMS[${i}]}",HEURISTIC="${HEURISTIC}",LIST_OF_SUBJECTS="--subjects ${SUBJECTS[${i}]}",LOCATOR="${LOCATOR}",OUTDIR="${SITE_LONG[${SITE}]}/bids/${sublong}",OVERWRITE="",POST="${POST}",SESSION_FOR_LONGITUDINAL="--ses ${SES[${i}]}",DEVICE_SERIAL_NUMBER="${DEVICE_SERIAL_NUMBER[${i}]}" \
        --bind ${BIND_DIR} \
        docker://${CONTAINER_IMAGE} \
            1> "${sublong}".out \
            2> "${sublong}".err &
            
    # starting to hit memory issues with this many scans
    if (( i == 6 )); then
        wait
    fi
done

wait

NEW_DIR="."
OUT_DIR=json_comparisons
mkdir -p ${OUT_DIR}
for i in "${!SUBJECTS[@]}"; do
    if [[ "${SUBJECTS[${i}]}" == *phantom* ]]; then
        printf 'skipping %s \n' "${sublong}"
        continue
    else
        sublong="${SITES[${i}]}${SUBJECTS[${i}]}${SES[${i}]}"
    fi

    printf '#### %s ####\n' "${sublong}"

    site_long="${SITE_LONG[${SITES[${i}]}]}"

    for json in "${NEW_DIR}"/"${site_long}"/bids/"${sublong}"/sub-*/ses-"${SES[${i}]}"/*/*json; do
        json_name=$(basename "${json}")
        common_path=$(realpath --relative-to ${NEW_DIR} "${json}")
        printf '## %s ##\n' "${json_name}"
        diff \
            <( jq --sort-keys 'del(.ConversionSoftwareVersion, .global, .time, .BidsGuess)' ${project}/"${common_path}") \
            <( jq --sort-keys 'del(.ConversionSoftwareVersion, .global, .time, .BidsGuess)' "${json}") \
            &> "${OUT_DIR}"/"${json_name%.*}"
        
    done
done