import datetime
import itertools
import json
from pathlib import Path

import polars as pl
from mri_actor_utils import config, models

# within docker container
JOB = Path("/opt/job.json")

# With too many participants per node, the workers fail with
# "fl:filesystem:FileExistsError" printed to the log. Unclear why, but
# the error seems to be generated by MATLAB.
N_SUBS_PER_NODE = 50

# for ls
MAX_NODES_PER_JOB = 6

# can change by incoming message by specifying "MAXJOBS"
MAXJOBS = N_SUBS_PER_NODE * MAX_NODES_PER_JOB

N_SEC_TO_COPY_ONE_SUB = 30


class QSIReconFSLReactor(models.Reactor):
    def get_runlist(self) -> tuple[list[str], list[str], list[str]]:
        if "qsirecon_fsl_dtifit" not in self.ilog.columns:
            ilog = self.ilog.with_columns(qsirecon_fsl_dtifit=0)
        else:
            ilog = self.ilog
        rundef = (
            ilog
            # exclude rows that were already processed
            .filter(pl.col("qsirecon_fsl_dtifit") == 0)
            .filter(pl.col("qsiprep") == 1)
            .with_columns(
                sublong=pl.concat_str(
                    pl.col("site"), pl.col("subject_id"), pl.col("visit")
                ),
                sitelong=pl.col("site").replace(config.SITE_LONG),
            )
            .with_columns(
                INPUT_DIR=pl.concat_str(
                    pl.lit("/corral-secure/projects/A2CPS/products/mris/"),
                    pl.col("sitelong"),
                    pl.lit("/qsiprep/"),
                    pl.col("sublong"),
                    pl.lit("/qsiprep"),
                )
            )
            .sort(
                "visit", "Surgery Week", "subject_id"
            )  # ensure V1 run before V3, and do oldest scans
        )

        runlist = (
            rundef.select(pl.col("INPUT_DIR"))
            .to_series()
            .to_list()[: self.maxjobs * self.n_submissions],
            rundef.select(pl.col("subject_id"))
            .to_series()
            .to_list()[: self.maxjobs * self.n_submissions],
            rundef.select(pl.col("visit"))
            .to_series()
            .to_list()[: self.maxjobs * self.n_submissions],
        )
        return runlist

    def parse_and_submit(self) -> None:
        print(json.dumps(self.context, indent=4))

        runlist = self.get_runlist()
        for r, (input_dirs, participant_labels, ses_labels) in enumerate(
            itertools.batched(runlist, self.maxjobs)
        ):
            n_jobs = len(input_dirs)
            if not n_jobs:
                raise RuntimeError("Did not find any jobs to submit")

            self.set_app_arg(
                name="INPUT_DIRS", value="--input-dirs " + " ".join(input_dirs)
            )
            self.set_app_arg(
                name="PARTICIPANT_LABELS",
                value="--participant-labels " + " ".join(participant_labels),
            )
            self.set_app_arg(
                name="SES_LABELS", value="--ses-labels " + " ".join(ses_labels)
            )
            self.job.name = f"{self.job_name}-{r}"

            self.set_common(n_jobs=n_jobs)
            self.submit()


def main() -> None:
    QSIReconFSLReactor(
        job_name=f"qsirecon-fsl-dtifit-{datetime.datetime.today().strftime('%Y-%m-%d')}",
        N_SUBS_PER_NODE=N_SUBS_PER_NODE,
        N_SEC_TO_COPY_ONE_SUB=N_SEC_TO_COPY_ONE_SUB,
        JOB=JOB,
        MAXJOBS=MAXJOBS,
    ).parse_and_submit()


if __name__ == "__main__":
    main()
