---
debug: false

logs:
  level: DEBUG
  token: ~

main:
  appId: urrutia-qaphantom-0.1
  name: qaphantom_job
  archive: true
  archivePath: ''
  maxRunTime: "00:30:00"
  parameters:
    BIND_DIR: "/corral-secure/projects/A2CPS"
    BIDS: /scratch1/08266/psadil/phantom/mris/SH_spectrum_health/bids/QC_SH043022QA
    OUTDIR: .
pipelines:
  api_server: https://portals-api.tacc.utexas.edu
  qaphantom_alias: qaphantom.prod
  